
CREATE DATABASE doingsdone
  DEFAULT CHARACTER SET utf8;

USE doingsdone;

CREATE TABLE User (
	ID_User INT AUTO_INCREMENT PRIMARY KEY,
	Name_User VARCHAR(128) NOT NULL,
	Email_User VARCHAR(128) NOT NULL ,
	Password CHAR(64) NOT NULL
);

CREATE TABLE Project (
	ID_Project INT AUTO_INCREMENT PRIMARY KEY,
	Name_Project VARCHAR(128),
	id_user INT NOT NULL
);

CREATE TABLE Task (
	ID_Task INT AUTO_INCREMENT PRIMARY KEY,
	Name_Task CHAR(128) NOT NULL,
	Creation_Date DATETIME DEFAULT NOW(),
	Execution_Date DATETIME,
	Status BOOLEAN DEFAULT FALSE,
	Term_Task DATETIME,
	FILE_TASK VARCHAR(1024),
	id_project INT
);